### PR TITLE
feat(upgrade): upgrade chart to latest version with CW tweaks

### PR DESCRIPTION
**Pull request by jfeldman325**
New Version of argo-cd chart with latest version.

### CODE REVIEW

**Comment by jfeldman325** [comment]
This is the most up to date chart I have for Argo-cd @ChandonPierre @brandonrjacobs . There was one previously in PR which I scrapped, but this has been deployed many times in tenant without issues afaik.

**Comment by ChandonPierre** [comment]
looks like a bit of a refactor at first glance - is this largely just fetch from upstream + re-apply CW specific stuff? if so can they be split into separate commits?

**Comment by jfeldman325** [comment]
> looks like a bit of a refactor at first glance - is this largely just fetch from upstream + re-apply CW specific stuff? if so can they be split into separate commits?

It's a re-apply and a bit of a refactor of the values. the upstream changed a bunch which is why it's lumped together. I personally don't have time to parse together all the changes.

**Comment by ChandonPierre** [comment]
closed in favor of #27

**Pull request closed without merging**
