### PR TITLE
feat(argo-cd): Merge Upstream changes

### PR DESCRIPTION
**Pull request by brandonrjacobs**
Merges upstream changes for what we care about.

### CODE REVIEW

**Comment by YitzyD** [comment]
Tested working?

**Comment by brandonrjacobs** [comment]
I deployed this version a while ago but I'd want to deploy again just to verify one last time. But seemed fine I recall.

**Comment by YitzyD** [comment]
> I deployed this version a while ago but I'd want to deploy again just to verify one last time. But seemed fine I recall.

When you feel comfortable with the update/test merge at will

**Comment by brandonrjacobs** [comment]
i'll go ahead and merge this since master isn't our deployable branch, coreweave is. Then i will re-verify once we pull it into coreweave branch.

**Pull request merged**
